### ISSUE TITLE
Error when co-located source maps

### ISSUE THREAD

**Issue by ivikash** [samccone/bundle-buddy#12]
Hey @samccone, I am trying to run `bundle-buddy src/**/*.map` but for all files its throwing `Error processing src/folderName/fileName.js.map, TypeError: Cannot read property 'split' of null` and ends with `No bundle source maps were processed.`

My source maps files are co-located with source files and not in public.

**Comment by samccone** [comment]
@ivikash I am guessing your source maps do not have the source content inside of the source maps files. You can verify this by opening one of your source map files and looking to see if the source is in there.

**Comment by ivikash** [comment]
Thanks, @samccone for your response. I can assure you those files are not empty.

**Comment by samccone** [comment]
interesting, would you be able to share a source map file with me so I can debug?

**Comment by samccone** [comment]
my guess would be it is this line that is failing
https://github.com/samccone/bundle-buddy/blob/15deed5102e81fdb2963b1e9aad302826ff8af86/process.ts#L91

**Comment by ivikash** [comment]
Probably. Let me try to do it locally.

**Comment by samccone** [comment]
Hi @ivikash going to close this. let me know if you have a test case for me and I can reopen.

Thanks

**Comment by felixbuenemann** [comment]
For me this error went away after adding the `devtool: 'source-map'` option in webpack with the initial setting in my case by Nuxt.js being `devtool: 'nosources-source-map'`. It would probably be good to have an error message instead of an exception here.

**Comment by samccone** [comment]
hi @felixbuenemann would you be able to create a test case that I could look at?

Thanks so much for reaching out!

**Comment by felixbuenemann** [comment]
I think this example will be useful:

https://github.com/webpack/webpack/tree/master/examples/source-map

It generates all the different source-map styles, you can then check the `nosources-source-map.js.map` with bundle-buddy.

**Comment by igorsantos07** [comment]
I'm having the same issue, which is weird because `source-map-explorer` works great and I've been using sourcemaps to debug my CRA app for a while now.

I guess I'll just drop the package? It seems it changed direction and this npm version got abandoned? The current README doesn't explain much...
