### ISSUE TITLE
Bundle Classifications

### ISSUE THREAD

**Issue by TheLarkInn** [samccone/bundle-buddy#19]
### Reference

webpack has 3 types of chunks (or as.most people call them, bundles) that are generated:

* Entry Chunk: this is a bundle that contains the webpack bootstrap/runtime code in it. 

* Initial Chunk: a chunk that does not have a runtime, and is usually generated via some configuration feature. It is loaded sync

* Normal Chunk: a chunk that does not have the runtime and is created by code-splitting (lazy). It is not called async on the page.

For the most part one can gather enough information with the source maps to classify a majority of the chunk types.

### Proposal
I'd like to propose the creation of an API that will help to classify bundles into these three categories based on their source and runtime contents.

To classify each:
* Entry Chunk: read source to see if it contains modules _and_ runtime code in single bundle

* Initial Chunk: Look for no runtime and only modules. Can typically be found by presence of modules wrapped in webpackJsonp function, however since this function name is configurable it's best to instead identify by lack of runtime. The second part is looking for the Entry chunk this chunk sync depends on. This will be identified by looking for the chunk initiator inside of the accompanying Entry chunk.

* Normal Chunk: this can be classified by a bundle having no runtime and the accompanying Entry chunk having no chunk initializer inside of the entry chunk (therefore indicating that it is loaded completely independent of the accompanying Entry chunk)

### Bonus Points
Since this tool is (mostly) webpack specific, we could also add an extra API that skips all this crazy classification work, and consumes a bit of metadata that describes all this info from webpack's emitted Stats object.

**Comment by TheLarkInn** [comment]
As I dug back into some of the sourcemap pieces of webpack, I noticed that it appears that webpack will mark when it's manifest has been extracted out, giving the path name: 

`webpack:///webpack/bootstrap`. This is simply perfect for identifying an entry chunk which has been extracted out to the runtime itself.

**Comment by samccone** [comment]
Is it possible for webpack to provide a mapping of bundles to "type" instead of depending on file content heuristics? I would like to keep this tool as generic as possible and I think having a concept of the following types of bundles

1. entry chunk
2. async chunk

would enable bundle-buddy to annotate things in a useful and generic way.

**Comment by TheLarkInn** [comment]
There's an entry bundle, sync bundle and async bundle. We could just classify as sync and non sync. And that might better get the message across. 

I think we can create a mapping with stats object but it's just a really huge json file. Maybe we can create a feature. Let me ponder on this one.

**Comment by TheLarkInn** [comment]
Could this be an optional parameter to the now exposed "process" function? That way I could pass it through via the plugin, and then we could PR a glob or "finder" for the same metadata in a persons build output dir.
