### ISSUE TITLE
Missing "Synthetic" Async Bundles 

### ISSUE THREAD

**Issue by TheLarkInn** [samccone/bundle-buddy#21]
When you use `CommonsChunkPlugin()` you can even remove duplication across async (lazy-loaded) chunks. 

However I noticed that somewhere, the "async commons chunk" is ignored and not added to the viz (maybe missed in graph too?).

### Steps to Reproduce:
1.  Clone [this repo](https://github.com/TheLarkInn/webpack-stress-test/blob/master/webpack.config.js)
2.  Comment out the `AgressiveSplittingPlugin()` (its so slow you'll get distracted and perf storm the plugin instead) from the webpack.config.js file, and add the property `devtool: "source-map"`
3.  Run `yarn build` See from results files like 0.0.bundle.js (should be a `async commons chunk`)
4. Run bundle-buddy against the dist folder where assets and maps are output. 

I'd help more with this for you but I'm working on some of the bundle type mapping code right now. 

Here is a screen shot (for example the bundle I'm saying was missing is `0.0.bundle.js.map`.
<img width="596" alt="screen shot 2017-07-16 at 5 34 15 pm" src="https://user-images.githubusercontent.com/3408176/28251988-52612138-6a4f-11e7-999b-f2ffcf6cb5eb.png">

**Comment by samccone** [comment]
thanks for the test case, I will take a look.
