### ISSUE TITLE
CI integration: Add return code

### ISSUE THREAD

**Issue by abergs** [samccone/bundle-buddy#23]
Hey,

I'd love to use bundle-buddy to make sure we do not have duplicates (especially important when you have singleton modules such as a store/cache).

Would like to add a return code, or -quiet flag so that we can just detect the status and fail the build if we have duplicates.

**Comment by samccone** [comment]
hmm sure, this should be quite straightforward to implement, however on most large applications some duplication is fine and expected.

thoughts?

**Comment by abergs** [comment]
@samccone So maybe default return 0 if no dupes or 1 if dupes, but add argument to configure:
--threshold 5
OR
--allowedDupicates /duplicates/ <-- regexp match allowed duplicated modules

If tests fail, return exit code 1 plus name/count of duplicates
else return 0?

Just starting with returning 0 or 1, and maybe the threshold args is a good v1.
Regexp support could come when someone ask for.

What do you think?

**Comment by erickwilder** [comment]
As a user of the tool is quite weird to see an  `Exit status 1` right after the execution did not report any duplication. The `--threshold` and/or allowing explicit duplicates would be an awesome addition.

**Comment by abergs** [comment]
@erickwilder It would only use exit code 1 if it finds duplicates during the  execution

/Anders (from phone)
________________________________

**Comment by samccone** [comment]
Can you expand on how the threshold bit would work... would it be per file or max duplication allowed in any bundle?

I think I understand what you are looking for... Some kind of way to use this tool in CI to prevent these kinds of overlap regressions... which does seem totally valid.

Let me know what you are thinking.

Thanks!

**Comment by abergs** [comment]
Unsure actually what my plan was... but I think unique number of modules being duplicated.

So if I know I have module X being duplicated in every module, the threshold to allow this would be —threshold 1. If module Y also is fine to duplicate it would be —threshold 2

I think I wanted it to just ignore some known duplications, while making sure my stores are not being duplicated which would cause all sorts of troubles.

Therefore the regex alternative would be a more robust alternative to mark modules as allowed to duplicate, but maybe a biter harder to implement.

/Anders (from phone)
________________________________
