### ISSUE TITLE
Graph area too small, bundles fall outside of space and are unreachable

### ISSUE THREAD

**Issue by paularmstrong** [samccone/bundle-buddy#24]
**Problem:** In large projects, some bundles are impossible to find in the graph area.
Example: 

<img width="2556" alt="screen shot 2017-07-26 at 11 18 50 am" src="https://user-images.githubusercontent.com/33297/28636825-4eee55aa-71f4-11e7-8a16-e74b4f9f6905.png">

As you can see, I have my browser extremely maximized and yet some bundles are falling out to the right of the screen. When the browser window is made smaller, this is the outcome:

<img width="1283" alt="screen shot 2017-07-26 at 11 20 18 am" src="https://user-images.githubusercontent.com/33297/28636863-6f0852d2-71f4-11e7-85d5-a9a4bf6728a8.png">

Notice that the bundles from the far left of the original  screenshot are missing and many from the right are also missing.

Details:
* bundle-buddy@0.1.2
* Chrome 60
* Webpack 2.4.1

**Comment by samccone** [comment]
hmm fair point, I wonder if we can muck with the forces if we detect the underlying graph is too large and then just regenerate. 

cc @susielu

**Comment by hydrosquall** [comment]
One option could be to add `d3-force-boundary` to push everything into the viewport (https://www.npmjs.com/package/d3-force-boundary )

![animation](https://raw.githubusercontent.com/john-guerra/d3-force/master/img/boundaryBorder.gif)

I'm guessing it might be added to https://github.com/samccone/bundle-buddy/blob/68480f4125a3cd7feef1a808d7c81939ca2b7124/viz/src/NetworkAnalysis.js#L48 , and possibly some places in `NetworkZoom` as well.
