### ISSUE TITLE
Why exit with status code 1 when no duplication is detected?

### ISSUE THREAD

**Issue by christianhg** [samccone/bundle-buddy#25]
The fact that `No bundle duplication detected 📯` sounds pretty successful makes me wonder why you don't exit with status code `0`. If I want to use `bundle-buddy` in my build step my build would fail if no duplication is detected 🙃

**Comment by samccone** [comment]
I can see your point about the exit code. However bundle buddy is not really a CI targeted tool, as some duplication is to be expected in an app, bundle-buddy is more about understanding where your duplication is coming from and optimizing from there.

thoughts?

**Comment by christianhg** [comment]
My thoughts are that I, for a moment, forgot the purpose of bundle-buddy. Thanks for an awesome tool, by the way 🙌 

I'm currently investigating the switch from a gulp based build to a webpack based build in a large project with many plugins that depend on a common core as well as each other. In the process my goal so far is to eliminate all duplication in these plugins, and this is probably why I got a bit hung up on the `No bundle duplication detected` success at the end of my build :)

That being said, my gut feeling is still that exit code `0` makes more sense since I really don't consider this an error.

**Comment by samccone** [comment]
I agree. This should be changed :)
