### ISSUE TITLE
Invalid 302 redirect when attempting to load

### ISSUE THREAD

**Issue by tivac** [samccone/bundle-buddy#30]
Every time I try to open the URL for my local bundle-buddy instance my browser breaks.

Here's what it looks like in FF:

![image](https://user-images.githubusercontent.com/49545/59623568-4b807400-90e9-11e9-8d42-58f20dafeecb.png)

And in Chrome:

![image](https://user-images.githubusercontent.com/49545/59623587-5a672680-90e9-11e9-9455-21a2481cd8cb.png)

I investigated further, here's what I'm seeing:

1. I run `npx bundle-buddy dist/*.map`
2. bundle-buddy runs, and opens a new tab in my default browser to `http://localhost:1024/?file=data_1560791818215`
3. That URL returns a 302 with a `location` header value of `//?file=data_1560791818215`
4. The browser ignores that invalid 302 value and throws up its hands

```bash
> npm --versions
{ '*********': '1.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.34.0',
  node: '10.15.3',
  openssl: '1.1.0j',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '6.8.275.32-node.51',
  zlib: '1.2.11' }
> node -p process.platform
win32
```

**Comment by vidinliev** [comment]
I'm facing the same issue. Tried switching between different versions of node, since I was getting the "[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated" warning on 12.4.0, but it still doesn't work.

**Comment by samccone** [comment]
Big thanks to @ian-craig for fixing this.

**Comment by tivac** [comment]
Thanks so much @ian-craig!

@samccone hope this isn't annoying but any guesses as to when you'll be able to publish the new version to npm?

**Comment by samccone** [comment]
bundle-buddy@0.2.2 is now published
